Update documentation for RockPi 4 booting
Linaro/trs pull request #7
Opened 2022-09-16 10:25 UTC by Leo-Yan

This patch set is to update documentation for RockPi 4 booting.

The first patch gives details for how to use U-boot command to detect USB stick, this can help developer to know if the USB port is compatible with the inserted USB stick.

The second patch gives method for only using SD card.

2022-09-22 18:46 UTC, chaws commented
LGTM, that's pretty much what I did to get my rockpi booting

2022-09-23 07:00 UTC, jbech-linaro requested changes

2022-09-23 07:36 UTC, Leo-Yan commented on docs/install/rockpi4.rst
> +into a single image and burn it into the SD card, this can be finished with
Will fix.

2022-09-23 07:36 UTC, Leo-Yan commented on docs/install/rockpi4.rst
> +.. code-block:: bash
Will fix.

2022-09-23 07:37 UTC, Leo-Yan commented
Thanks for reviewing, @chaws and @jbech-linaro .  Have updated the patches for Joakim's comments.

2022-09-23 07:39 UTC, merged